#Это настройки Pytest
[pytest]
# Опция для автоматического добавления флагов
addopts = -s -v
# Устанавливает правила для тестовых файлов
python_files = *_tests.py test_*.py
# Устанавливает правила для имен классов
python_classes = Test*
# Устанавливает правила для имен функций
python_functions = test_*

#Регистрируем кастомные маркировки
markers=
    regression : Маркировка тестов регресса
    auth : Маркировка тестов аутенфикации
    abonent : Маркировка тестов папки абонент
    advisers : Маркировка тестов с адвайзерами
    banners : Маркировка тестов с баннерами
    department: Маркировка тестов с подразделениями